title: Daniel Bergamin
email: daniel@bergam.in
description: >- # ignore newlines until "baseurl:"
  You're visiting the personal site of Daniel Bergamin. I'm interested in the people, technologies 
  and systems that underpin the modern web and like to <a href="/blog/">write about them</a> sometimes.
baseurl: ""
url: "https://danielbergamin.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dbergamin

contact_email: daniel@bergam.in
contact_name: Daniel Bergamin
contact_telephone: +44 7903 104727

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .gitignore
