title: Daniel Bergamin
email: daniel@bergam.in
description: >- # this means to ignore newlines until "baseurl:"
  The personal site of Daniel Bergamin. I have a broad interest in the
  people, technologies and systems that underpin the modern web.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielbergamin.net" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dbergamin

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .gitignore
